package ch.hftm.service;

import ch.hftm.data.Album;
import com.jayway.jsonpath.JsonPath;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AlbumServiceTest {

    private static String json;
    private static final File jsonFile = new File("storage/albums.json");
    AlbumService albumService = new AlbumService();

    private static String readFile() throws IOException {
        return Files.readString(AlbumServiceTest.jsonFile.toPath(), StandardCharsets.UTF_8);
    }

    @BeforeAll
    public static void init() throws IOException {
        json = readFile();
    }

    @Test
    void createAlbum() throws IOException {
        Album testAlbum = new Album("TestAlbum", "Test Description");
        albumService.createAlbum("TestAlbum", "Test Description");

        // read json file which was generated by createAlbum and check if the values match
        assertEquals(testAlbum.getName(), JsonPath.read(json, "$.name"));
        assertEquals(testAlbum.getDescription(), JsonPath.read(json, "$.description"));
    }
}