package ch.hftm.service;

import ch.hftm.data.Album;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;

class AlbumServiceTest {

    private static final File jsonFile = new File("storage/albums.json");
    AlbumService albumService = new AlbumService();


    @Test
    void createAlbum() throws IOException {
        Album testAlbum = new Album("Vacation", "Vacation Album");
        albumService.createAlbum("Vacation", "Vacation Album");
//
//        String json = Files.readString(AlbumServiceTest.jsonFile.toPath(), StandardCharsets.UTF_8);
//
//        // read json file which was generated by createAlbum and check if the values match
//        assertEquals(testAlbum.getName(), JsonPath.read(json, "$.name"));
//        assertEquals(testAlbum.getDescription(), JsonPath.read(json, "$.description"));
    }
}